### PR TITLE
adds basic topic integration and a topic column to the data view

### PR DESCRIPTION
**Pull request by Teikahym**
Adds basic topic integration to the db and both python writer-scripts. 
Adds a new topic column to the data view. 
To keep things simple and in line with the cloud-based dms, the topic-strings defined in the PaPi dms-lite examples should be used. 

This new topic field can be a basis for future data-sorting and visualization features (see Refs). 

Fixes: https://github.com/Project-Owl/dms-lite/issues/20, https://github.com/Project-Owl/dms-lite/issues/21

Refs: https://github.com/Project-Owl/dms-lite/issues/16

### CODE REVIEW

**Comment by TimoWielink** [comment]
This looks great! Thank you, let me test real quick and then merge!

**Comment by Teikahym** [comment]
Changes to the PaPi dms-lite examples can be viewed here: https://github.com/Teikahym/ClusterDuck-Protocol/commit/42f61be31e9cc0cedc649052de60b1ff93a0f3e3

Should I create a pull request for the main Repository (Call-for-Code) or the Project-OWL fork?

**Comment by TimoWielink** [comment]
If you would like to create the Pull Request to the ClusterDuck Protocol Call For Code repository. 

Thank You we are currently working on the DMS-Lite Updates.

**Comment by nfeuer** [comment]
The Call-For-Code repository is the official open-source repository. We use the Project OWL fork to make pull requests to the Call-For-Code repository.

Code looks great!

**Review by nfeuer — APPROVED** [review]

**Pull request merged**
